RUN = iverilog -g2009
SRCS = /home/meltpoint/verirunner/testcase/FFT/FIFO.sv /home/meltpoint/verirunner/testcase/FFT/reoder.sv /home/meltpoint/verirunner/testcase/FFT/FFT_unit.sv /home/meltpoint/verirunner/testcase/FFT/top.sv /home/meltpoint/verirunner/testcase/FFT/top_sim.sv /home/meltpoint/verirunner/testcase/FFT/shift_reg.sv /home/meltpoint/verirunner/testcase/FFT/FFT_unit_sim.sv /home/meltpoint/verirunner/testcase/FFT/butt2.sv
TARGET = a.out

$(TARGET): $(SRCS)
	$(RUN) $(SRCS)
